import { toast } from "sonner";
import { useSession } from "next-auth/react";
import { useCompaniesQuery, useCompanyQuery, useCompanyStatsQuery, useCreateCompanyMutation, useDeleteCompanyMutation, useUpdateCompanyMutation } from "@/lib/api";
import type { CreateCompanyPayload, ListCompaniesParams, UpdateCompanyPayload } from "@/types/company";

export const useCompanies = (params: ListCompaniesParams) => { const { data: s } = useSession(); return useCompaniesQuery({ params, token: s?.accessToken }, { skip: !s?.accessToken }); };
export const useCompany = (companyId: string) => { const { data: s } = useSession(); return useCompanyQuery({ companyId, token: s?.accessToken }, { skip: !companyId || !s?.accessToken }); };
export const useCompanyStats = (companyId: string) => { const { data: s } = useSession(); return useCompanyStatsQuery({ companyId, token: s?.accessToken }, { skip: !companyId || !s?.accessToken }); };
export const useCreateCompany = () => { const { data: s } = useSession(); const [trigger, state] = useCreateCompanyMutation(); const mutate = (payload: CreateCompanyPayload) => trigger({ payload, token: s?.accessToken }).unwrap().then(() => toast.success("Company created")).catch((e) => toast.error(e.message || "Failed to create company")); return { ...state, isPending: state.isLoading, mutate, mutateAsync: mutate }; };
export const useUpdateCompany = (companyId: string) => { const { data: s } = useSession(); const [trigger, state] = useUpdateCompanyMutation(); const mutate = (payload: UpdateCompanyPayload) => trigger({ companyId, payload, token: s?.accessToken }).unwrap().then(() => toast.success("Company updated")).catch((e) => toast.error(e.message || "Failed to update company")); return { ...state, isPending: state.isLoading, mutate, mutateAsync: mutate }; };
export const useDeleteCompany = () => { const { data: s } = useSession(); const [trigger, state] = useDeleteCompanyMutation(); const mutate = (companyId: string) => trigger({ companyId, token: s?.accessToken }).unwrap().then(() => toast.success("Company removed")).catch((e) => toast.error(e.message || "Failed to remove company")); return { ...state, isPending: state.isLoading, mutate, mutateAsync: mutate }; };
